let productGirl = [
 {
  id: 1,
  title: "Cheese Beef Hamburger",
  image: "/97/16-menu-CheeseBeefHamburger.png", 
  starCount: 4,
  price: 7.2
 },
 { id: 2, title: "watch 29100 (ضد آب)", image: "/97/watch.jpg", starCount: 999, price: 300 },
 { id: 3, title: "‌watch digitaling 882", image: "/97/watch-digital.jpg", starCount: 2, price: 50 },
 { id: 4, title: "combo fun ‌Chicken sokharii", image: "/97/19-menu-comboFun.png", starCount: 5, price: 5 },
 { id: 5, title: "‌apple watch 2024", image: "/97/watch-apple.jpg", starCount: 4, price: 450 },
 { id: 6, title: "spiker vary high vloum 2024", image: "/97/section_of_product-spicker.webp", starCount: 5, price: 100 },
 { id: 7, title: "‌Chicken with Spicy Sauce", image: "/97/20-menu-chicken-with.png", starCount: 4, price: 4 },
 { id: 8, title: "‌playstasion 5 512gb", image: "/97/ps5.webp", starCount: 5, price: 250 },
 { id: 9, title: "pepsi soda", image: "/97/pepsi.jpg", starCount: 4, price: 3 },
 { id: 10, title: "‌salad vagtabole", image: "/97/21-menu-salad.png", starCount: 4, price: 6 },
 { id: 11, title: "mouse no sim", image: "/97/mouse.jpg", starCount: 4, price: 75},
 { id: 12, title: "mac book 2024 ram : 12gb / hard : 1T SSD", image: "/97/main-laptop.webp", starCount: 5, price: 800 },
 { id: 13, title: "‌Chicken Barger", image: "/97/22-menu-chickenBarger.png", starCount: 5, price: 5 },
 { id: 14, title: "gaming case graphic 4090 8gb", image: "/97/main-gaming_pc.webp", starCount: 5, price: 1_200 },
 { id: 15, title: "hp core i7 12000 ram 16gb 1T sSD", image: "/97/lapTop-hp.jpg", starCount: 4, price: 350 },
 { id: 16, title: "Lipton yummy", image: "/97/23-menu-Lipton.png", starCount: 5, price: 8.5 },
 { id: 17, title: "lap top for developer i5 9000 ram 16gb", image: "/97/lapTop-hp2.jpg", starCount: 3, price: 250 },
 { id: 18, title: "‌keyboard no sim", image: "/97/keyboard.jpg", starCount: 8, price: 125 },
 { id: 19, title: "airpad with 12hour charge", image: "/97/airpad.jpg", starCount: 4, price: 120 },
 { id: 20, title: "iPhone x 4gb 512gb", image: "/97/iphone-x.jpg", starCount: 4, price: 250 },
 { id: 21, title: "iPhone 12 pro max 6gb 1T", image: "/97/iphone-12_pro_max.jpg", starCount: 4, price: 400 },
 { id: 22, title: "‌airpad apple with 8hour charge", image: "/97/airpad2.jpg", starCount: 3, price: 140 },
 { id: 23, title: "T-Shirt M gang", image: "/97/image1.png", starCount: 5, price: 100 },
 { id: 24, title: "headphone with 12hour charge", image: "/97/headphone.jpg", starCount: 4, price: 50 },
 { id: 25, title: "banana", image: "/97/banana.jpg", starCount: 5, price: 0.99 },
 { id: 26, title: "tv 8k", image: "/97/discounts-tv.webp", starCount: 5, price: 1250 },
 { id: 27, title: "‌charger no sim", image: "/97/discounts-mater.webp", starCount: 4, price: 320 },
 { id: 28, title: "cap cake", image: "/97/capcake.jpg", starCount: 2, price: 1.99 },
 { id: 29, title: "coffe", image: "/97/coffe.jpg", starCount: 4, price: 7.2 },
 { id: 30, title: "cocacola", image: "/97/cocacola.jpg", starCount: 5, price: 5 },
]
export default productGirl